{
 "title": "Pizza Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-logs\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Pizza creation latency (dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "pizzaCreationLatency_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza creation latency (ms)"
    }
   ]
  },
  {
   "title": "Service latency (dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "serviceLatency_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Request latency (ms)"
    }
   ]
  },
  {
   "title": "Pizza purchases/minute (dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(pizzasSoldCount_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizzasFailedCount_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Revenue/minute (dev)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenueTotal_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentication attempts/minute (dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "rate(successAuthCount_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(failedAuthCount_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Active users (dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "activeUsersCount_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Number of users"
    }
   ]
  },
  {
   "title": "HTTP requests/minute (dev)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(countAll_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "ALL"
    },
    {
     "expr": "rate(countDeletes_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(countGets_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(countPosts_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(countPuts_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "title": "System usage (%) (dev)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpuUsage_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "CPU"
    },
    {
     "expr": "memoryUsage_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "HTTP Request Rate (Assignment)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}